// <auto-generated />
namespace PharmaSoftware_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Change_property_password_to_passwordHash : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_property_password_to_passwordHash));
        
        string IMigrationMetadata.Id
        {
            get { return "202011261821029_Change_property_password_to_passwordHash"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
